---
deployment:
  tasks:
    - "/bin/bash -lc 'cd /home/u1656986/public_html/repositories/portal-kopmaugm.com && timeout 300 php artisan migrate --force --no-interaction && php artisan optimize:clear'"
